### ISSUE TITLE
Pusher PUSHER_APP_KEY changed

### ISSUE THREAD

**Issue by r00tpt** [zSoulweaver/kient#17]
Hey.
Just notice that i was getting connection closed and that kick was haing some issues. They kind of resolve them and changed the `PUSHER_APP_KEY` from `eb1d5f283081a78b932c` to `32cbd69e4b950bf97679`.

So anyone having the same issue just needs to updated the `PUSHER_APP_KEY`

**Comment by zSoulweaver** [comment]
Yep, fork it and fix it, submit a PR if you want and I'll merge it. If I find the time I'll update the key and maybe I'll also provide an option when creating the Kient instance to provide a key if Kick decide to change it again for no reason.

I've taken a slight step back updating Kient whilst Kick get their act together and release the actual API, I didn't think it would have been this far away. :(

**Comment by KadirFiratFTW** [comment]
> Yep, fork it and fix it, submit a PR if you want and I'll merge it. If I find the time I'll update the key and maybe I'll also provide an option when creating the Kient instance to provide a key if Kick decide to change it again for no reason.
> 
> I've taken a slight step back updating Kient whilst Kick get their act together and release the actual API, I didn't think it would have been this far away. :(

I forked and created PR for this fix

**Comment by zSoulweaver** [comment]
> I forked and created PR for this fix

#18 Merged and new release published, thanks :)
