### ISSUE TITLE
Cycle TLS timed out!

### ISSUE THREAD

**Issue by Jagjeet0518** [zSoulweaver/kient#2]
I've tried making a similar bot by using your code. but i get timeout initialising Cycle TLS. it also happens when i am using the "kient" package.

**Comment by zSoulweaver** [comment]
Have you tried using CycleTLS on its own outside of this library? If you are having issues with CycleTLS outside of this library I would suggest raising an issue on the CycleTLS repo. 

Could you share some more information about how you are using CycleTLS? Are you running it on a server? Do you have issues requesting non kick.com urls with it? Etc.

**Comment by Holovin** [comment]
Seems same issue

[error] uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Could not connect to the CycleTLS instance within 4000ms".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Could not connect to the CycleTLS instance within 4000ms".

**Comment by Holovin** [comment]
https://github.com/Danny-Dasilva/CycleTLS/issues/300

Find related issue in used lib, just for other guys who face with same issu
