### ISSUE TITLE
Feature request: export api interfaces

### ISSUE THREAD

**Issue by Satont** [zSoulweaver/kient#3]
It might be good if all api responses be exported, so i can cache them in my application and do not call kick api, specially noticed they are not exported on `getCurrentUser`.

I'm familiar to do PR if you wan't to.

**Comment by zSoulweaver** [comment]
Absolutely agree, I was just too lazy to setup the exports originally. I committed some changes last night to assist with this.

I have setup barrel files and I'm just exporting everything currently. I'm not that familiar with setting up exports for a library so I'm not sure is there is a better way to achieve this. I'll just need to publish to npm if it looks good, I can do so after work today, looking at about ~12 hours away, unless I get time this morning.

**Comment by Satont** [comment]
Ok, thanks.

And thanks for your library, i found it pretty useful for myself.

**Comment by zSoulweaver** [comment]
Found some time this morning, published `v1.0.1-8` to NPM.
